name: Cubs Win Notifier

on:
  schedule:
    # Runs every day at specified intervals
    - cron: "0 16 * * *" # 11am CDT
    - cron: "0 21 * * *" # 4pm CDT
    - cron: "0 0 * * *" # 7pm CDT (next day in UTC)
    - cron: "0 4 * * *" # 11pm CDT (next day in UTC)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Import secrets
        env:
          GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
          SENDER: ${{ secrets.SENDER }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
        run: |
          echo "$GMAIL_CREDENTIALS" > client_secret.json
          echo "$GMAIL_TOKEN" > token.json
          echo "$SENDER" > sender.txt
          echo "$RECIPIENT" > recipient.txt

      - name: Run Cubs Win Notifier
        run: |
          python run.py

      - name: Read timestamp and message
        id: read-files
        run: |
          echo "::set-output name=timestamp::$(cat timestamp.txt)"
          echo "::set-output name=message::$(cat message.txt)"

      - name: Update README
        run: |
          TIMESTAMP="${{ steps.read-files.outputs.timestamp }}"
          MESSAGE="${{ steps.read-files.outputs.message }}"
          sed -i '/<!-- start-timestamp -->/,/<!-- end-timestamp -->/c\<!-- start-timestamp -->\n'"$TIMESTAMP"'\n<!-- end-timestamp -->' README.md
          sed -i '/<!-- start-message -->/,/<!-- end-message -->/c\<!-- start-message -->\n'"$MESSAGE"'\n<!-- end-message -->' README.md

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest game status"
          git push
